buah/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='buah/index'),
    path('data_master/', views.data_master, name='buah/data_master'),
    path('tambah_data_master/', views.tambah_data_master, name='buah/tambah_data_master'),
    path('proses_tambah_data_master/', views.proses_tambah_data_master, name='buah/proses_tambah_data_master'),
    path('hapus_data/', views.hapus_data, name='buah/hapus_data'),
    path('detail_gambar/', views.detail_gambar, name='buah/detail_gambar'),
    path('download_csv/', views.download_csv, name='buah/download_csv'),
    path('data_anfis/', views.data_anfis, name='buah/data_anfis'),
    path('tambah_model/', views.tambah_model, name='buah/tambah_model'),
    path('proses_pelatihan/', views.proses_pelatihan, name='buah/proses_pelatihan'),
    path('hapus_anfis/', views.hapus_anfis, name='buah/hapus_anfis'),
    path('lihat_anfis/<int:model_id>/', views.lihat_anfis, name='buah/lihat_anfis'),
    path('pengujian/', views.pengujian, name='buah/pengujian'),
    path('proses_pengujian/', views.proses_pengujian, name='buah/proses_pengujian'),
]

sistem_buah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('index_lama', views.index_lama, name="index_lama"),
    path('admin/', admin.site.urls),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('process_login', views.process_login, name="process_login"),
    path('pengujian', views.pengujian, name="pengujian"),
    path('process_pengujian', views.process_pengujian, name="process_pengujian"),
    path('buah/', include('buah.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buah/models.py
from django.db import models
from django_pandas.managers import DataFrameManager
# Create your models here.
import json

class Dataset(models.Model):
    filename = models.ImageField(upload_to="uploads")
    form_factor = models.FloatField(null=True, blank=True)
    aspect_ratio = models.FloatField(null=True, blank=True)
    rect = models.FloatField(null=True, blank=True)
    narrow_factor = models.FloatField(null=True, blank=True)
    prd = models.FloatField(null=True, blank=True)
    plw = models.FloatField(null=True, blank=True)
    mean_h = models.FloatField(null=True, blank=True)
    mean_s = models.FloatField(null=True, blank=True)
    mean_v = models.FloatField(null=True, blank=True)

    MALACCENSIS = 0
    MICROCARPA = 1

    KELAS_CHOICES = [
        (MALACCENSIS, 'MALACCENSIS'),
        (MICROCARPA, 'MICROCARPA'),
    ]
    kelas = models.IntegerField(null=True, blank=True, choices=KELAS_CHOICES)


class Model(models.Model):
    filename = models.FileField(upload_to="models")
    datalatih_ids = models.TextField(null=True, blank=True)
    datauji_ids = models.TextField(null=True, blank=True)
    accuracy = models.FloatField(null=True, blank=True)
    epoch = models.IntegerField(null=True, blank=True, default=1)

    @property
    def jumlah_data_latih(self):
        json_datalatih_ids = json.loads(self.datalatih_ids)

        return  len(json_datalatih_ids)

    @property
    def jumlah_data_uji(self):
        json_datauji_ids = json.loads(self.datauji_ids)

        return  len(json_datauji_ids)

buah/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse, Http404
from .models import Dataset, Model
from django.core.files.base import ContentFile
import base64
from .libraries.feature_extraction_factory import FeatureExtractionFactory
import uuid
import numpy as np
import cv2
from PIL import Image
from pprint import pprint
from sklearn.model_selection import StratifiedKFold
from itertools import islice, count
import json
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pickle
import os
from os.path import join
from django.conf import settings
import csv
import tempfile
from utils.helper import get_second_value, get_url_citra
import pandas as pd

def index(request):
    if not request.user.is_authenticated:
        return redirect("index")
    return render(request, 'dashboard.html')


def data_master(request):
    if not request.user.is_authenticated:
        return redirect("index")
    datasets = Dataset.objects.all()
    context = {
        "datasets": datasets,
    }
    return render(request, 'buah/data-master.html', context)

def tambah_data_master(request):
    return render(request, 'buah/tambah-data-master.html')

def proses_tambah_data_master(request):
    if not request.user.is_authenticated:
        return redirect("index")
    QueryDict = request.POST
    image64 = QueryDict.get('image')
    kelas = QueryDict.get('kelas')
    formatt, imgstr = image64.split(';base64,')
    ext = formatt.split('/')[-1]
    filename = str(uuid.uuid4())
    fileImg = ContentFile(base64.b64decode(imgstr), name=filename + "." + ext)
    image = cv2.imdecode(np.fromstring(fileImg.read(), np.uint8), 1)

    factory = FeatureExtractionFactory()
    morfologi = factory.make_morfologi(image)
    image_gray = morfologi.gray
    image_binary = morfologi.cleaned.astype(int)*255



    image_clean = base64.b64encode(cv2.imencode('.png', image)[1]).decode()
    image_gray = base64.b64encode(cv2.imencode('.png', image_gray)[1]).decode()
    image_binary = base64.b64encode(cv2.imencode('.png', image_binary)[1]).decode()

    hsv = factory.make_hsv(image)


    prd      =  morfologi.get_prd()
    plw      =  morfologi.get_plw()
    rect     =  morfologi.get_rect()
    nf       =  morfologi.get_narrow_factor()
    ar       =  morfologi.get_aspect_ratio()
    ff       =  morfologi.get_form_factor()

    mean_h      = hsv.get_mean_h()
    mean_s  = hsv.get_mean_s()
    mean_v      = hsv.get_mean_v()

    dataset = Dataset()
    dataset.filename = fileImg
    dataset.form_factor = ff
    dataset.aspect_ratio = ar
    dataset.rect = rect
    dataset.narrow_factor = nf
    dataset.prd = prd
    dataset.plw = plw

    dataset.mean_h = mean_h
    dataset.mean_s = mean_s
    dataset.mean_v = mean_v
    dataset.kelas = kelas
    dataset.save()

    success = 1
    context = {
        'success': success,
        'image_clean': image_clean,
        'image_gray': image_gray,
        'image_binary': image_binary
    }
    return JsonResponse(context, safe=False)

def hapus_data(request):
    data_id = request.POST.get('data_id')
    data = Dataset.objects.get(id=data_id)
    data.filename.delete()
    data.delete()

    success = 1
    context = {
        'success': success
    }
    return JsonResponse(context, safe=False)


def detail_gambar(request):
    id = int(request.POST.get('id'));
    dataset = Dataset.objects.get(id=id)
    filepath = dataset.filename.path
    image = cv2.imread(filepath)
    R = image[:, :, 2]
    G = image[:, :, 1]
    B = image[:, :, 0]

    factory = FeatureExtractionFactory()
    morfologi = factory.make_morfologi(image)

    image_gray = morfologi.gray
    image_binary = morfologi.cleaned.astype(int)*255

    image_clean = base64.b64encode(cv2.imencode('.png', image)[1]).decode()
    image_gray = base64.b64encode(cv2.imencode('.png', image_gray)[1]).decode()
    image_binary = base64.b64encode(cv2.imencode('.png', image_binary)[1]).decode()

    hsv = factory.make_hsv(image)


    h = hsv.h
    s = hsv.s
    v = hsv.v
    image_h = base64.b64encode(cv2.imencode('.png', h)[1]).decode()
    image_s = base64.b64encode(cv2.imencode('.png', s)[1]).decode()
    image_v = base64.b64encode(cv2.imencode('.png', v)[1]).decode()

    success = 1
    context = {
        'success': success,
        'image_clean': image_clean,
        'image_gray': image_gray,
        'image_binary': image_binary,
        'image_h': image_h,
        'image_s': image_s,
        'image_v': image_v,
    }

    return JsonResponse(context, safe=False)

def download_csv(request):
    tipe = request.GET.get("type")
    data_id = int(request.GET.get("id"))

    dataset = Dataset.objects.get(id=data_id)
    filepath = dataset.filename.path
    image = cv2.imread(filepath)

    R = image[:, :, 2]
    G = image[:, :, 1]
    B = image[:, :, 0]

    factory = FeatureExtractionFactory()
    morfologi = factory.make_morfologi(image)

    image_gray = morfologi.gray
    image_binary = morfologi.cleaned.astype(int)*255



    image_to_download = ""

    if (tipe == "R"):
        image_to_download = R
    elif (tipe == "G"):
        image_to_download = G
    elif (tipe == "B"):
        image_to_download = B
    elif (tipe == "gray"):
        image_to_download = image_gray
    elif (tipe == "binary"):
        image_to_download = image_binary
    else:
        raise Http404


    namafile = "{}_{}.csv".format(tipe, str(data_id))
    handle, fn = tempfile.mkstemp(suffix='.csv')
    with os.fdopen(handle,"w", encoding='utf8',errors='surrogateescape',\
                  newline='') as f:
        writer=csv.writer(f)
        for row in image_to_download:
            try:
                writer.writerow(row)
            except Exception as e:
                print ('Error in writing row:',e)
        f.close()

    response = None

    with open(fn, 'rb') as fh:
        response = HttpResponse(
            fh.read(), content_type="text/csv")
        response['Content-Disposition'] = 'inline; filename=' + namafile
    os.remove(fn)
    return response

    raise Http404


def data_ekstraksi(request):
    if not request.user.is_authenticated:
        return redirect("index")
    return HttpResponse('welcome')
    pass


def data_anfis(request):
    if not request.user.is_authenticated:
        return redirect("index")
    models = Model.objects.all()

    context = {
        'models': models
    }
    return render(request, 'buah/data-anfis.html', context)


def tambah_model(request):
    if not request.user.is_authenticated:
        return redirect("index")
    return render(request, 'buah/tambah-model.html')


def proses_pelatihan(request):
    if not request.user.is_authenticated:
        return redirect("index")
    from buah.libraries.anfis_matlab import AnfisMatlab
    import matlab
    import matlab.engine
    os.makedirs("media/fis", exist_ok=True)
    os.makedirs("media/models", exist_ok=True)
    os.makedirs("media/uploads", exist_ok=True)

    simpan = int(request.POST.get('simpan')
                 ) if request.POST.get('simpan') else -1
    epoch = int(request.POST.get('epoch')) if request.POST.get('epoch') else 1
    persen_uji = float(request.POST.get('persen_uji')) if request.POST.get(
        'persen_uji') else float(20)

    dataset = pd.DataFrame(list(Dataset.objects.all().values()))
    columns = ['id', 'form_factor', 'aspect_ratio', 'rect',
               'narrow_factor', 'prd', 'plw', 'mean_h', 'mean_s', 'mean_v', 'kelas']
    df = dataset.loc[:, columns].copy()
    persen_uji = persen_uji / 100
    train_df, test_df = train_test_split(
        df, test_size=persen_uji, stratify=df.loc[:, ['kelas']], random_state=0)
    train_df = train_df.sort_index()
    test_df = test_df.sort_index()


    train_data = train_df.copy()
    test_data = test_df.copy()

    X_train = train_data.loc[:, ~train_data.columns.isin(['id', 'kelas'])]
    Y_train = train_data.loc[:, train_data.columns.isin(['kelas'])]
    X_test = test_data.loc[:, ~test_data.columns.isin(['id', 'kelas'])]
    Y_test = test_data.loc[:, test_data.columns.isin(['kelas'])]

    scaler = MinMaxScaler()
    scaler.fit(X_train)

    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    X_train_scaled_with_class = np.concatenate(
        (X_train_scaled, Y_train.to_numpy()), axis=1)

    X_test_scaled_with_class = np.concatenate(
        (X_test_scaled, Y_test.to_numpy()), axis=1)

    Y_test_reshape = Y_test.to_numpy().reshape(-1)
    engine = matlab.engine.find_matlab()[0]
    engine = matlab.engine.connect_matlab(engine)
    matlablibdir = join(settings.BASE_DIR, 'matlab')
    engine.cd(matlablibdir)
    am = AnfisMatlab(engine)
    filename = str(uuid.uuid4())
    radii = 0.5
    savefis = join(settings.MEDIA_ROOT, 'fis', filename + ".fis")
    dirfis = am.create_fis(X_train_scaled, Y_train.to_numpy(), radii, savefis)

    am.mulai_pelatihan(X_train_scaled_with_class, dirfis, epoch, dirfis)
    predicted = am.mulai_pengujian(X_test_scaled, dirfis)
    flat_predicted = np.concatenate(predicted)
    num_correct = int(np.sum(flat_predicted == Y_test_reshape))

    test_data = test_data.astype({"kelas": int})
    test_data['kelas_predicted'] = flat_predicted.reshape(-1, 1)


    accuracy = float((num_correct / Y_test.count()) * 100)

    train_data_ids = train_data['id'].tolist()
    test_data_ids = test_data['id'].tolist()

    pickle_data = {
        'model': dirfis,
        'train_data': train_data,
        'test_data': test_data,
        'train_data_scaled':X_train_scaled_with_class,
        'test_data_scaled':X_test_scaled_with_class,
        'train_data_ids': train_data_ids,
        'test_data_ids': test_data_ids,
        'epoch': epoch,
        'accuracy': accuracy,
        'num_correct': num_correct,
        'scaler':  scaler,
    }

    dirwithfilename = join('models', filename + ".pkl")
    path = join(settings.MEDIA_ROOT, dirwithfilename)

templates/buah/data-anfis.html
{% extends "base.html" %}
{% load static %}
{% block export-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/cropperjs/dist/cropper.min.css' %}">
{% endblock export-css %}
{% block css %}
<style type="text/css">
th {
  text-align: center;
}
</style>
{% endblock css %}
{% block content %}

<h2 class="title-heading">Data ANFIS</h2>

<button type="button" id="btn-tambah" onclick="location.href='{% url 'buah/tambah_model' %}'" class="btn btn-primary btn-tambah">Buat Model Baru</button>

<br />


<table id="table-model-anfis" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th width="5%">ID</th>
      <th>Data Latih</th>
      <th>Data Uji</th>
      <th>Epoch</th>
      <th>Akurasi</th>
      <th width="17%">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for model in models %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ model.jumlah_data_latih }}</td>
      <td>{{ model.jumlah_data_uji }}</td>
      <td>{{ model.epoch }}</td>
      <td>{{ model.accuracy }}</td>
      <td>


        <button  class="btn btn-danger btn-sm btn-icon icon-left btn-hapus" onclick="hapusAnfis({{ model.id }})">
          <i class="entypo-cancel"></i>
          Delete
        </button>
        <button  class="btn btn-info btn-sm btn-icon icon-left btn-detail" onclick="location.href='{% url 'buah/lihat_anfis' model.id %}'">
          <i class="entypo-list"></i>
          Detail
        </button>
        
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

{% block export-js %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/cropperjs/dist/cropper.min.js' %}"></script>
{% endblock export-js %}

{% block js %}
<script>

$("#table-model-anfis").DataTable();

function hapusAnfis(model_id) {
  var model_id = model_id
  axios.post('{% url "buah/hapus_anfis" %}', Qs.stringify({ 
    model_id: model_id
  }))
  .then((res) => {
    data = res.data
    if (data.success == 1) {
      window.location.reload(false);
    }
  })
}
</script>
{% endblock js %}

templates/buah/data-master.html
{% extends "base.html" %}
{% load static %}
{% block export-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/cropperjs/dist/cropper.min.css' %}">
{% endblock export-css %}
{% block css %}
<style type="text/css">
.image-data {
  max-width: 100%;
}
</style>
{% endblock css %}
{% block content %}

<h2 class="title-heading">Data Master</h2>
<button type="button" class="btn-tambah btn btn-primary" onclick="location.href='{% url 'buah/tambah_data_master' %}'" class="btn btn-primary btn-tambah">Tambah Data</button>
<br />


<table id="table-data-master" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>NO</th>
      <th>GAMBAR</th>
      <th>MEAN H</th>
      <th>MEAN S</th>
      <th>MEAN V</th>
      <th>ASPECT_RATIO</th>
      <th>FORM_FACTOR</th>
      <th>RECT</th>
      <th>NARROW_FACTOR</th>
      <th>PRD</th>
      <th>PLW</th>
      <th>KELAS</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for dataset in datasets %}
    <tr data-model-id="{{ dataset.id }}">
      <td>{{ forloop.counter }}</td>
      <td><img  class="image-data"  src="{{   dataset.filename.url  }}" alt=""></td>
      <td>{{ dataset.mean_h }}</td>
      <td>{{ dataset.mean_s }}</td>
      <td>{{ dataset.mean_v }}</td>
      <td>{{ dataset.aspect_ratio }}</td>
      <td>{{ dataset.form_factor }}</td>
      <td>{{ dataset.rect }}</td>
      <td>{{ dataset.narrow_factor }}</td>
      <td>{{ dataset.prd }}</td>
      <td>{{ dataset.plw }}</td>
      <td>{{ dataset.get_kelas_display }}</td>
      <td>
        <button  class="btn btn-danger btn-sm btn-icon icon-left btn-hapus" onclick="deleteData({{ dataset.id }})">
          <i class="entypo-cancel"></i>
          Delete
        </button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Default Modal</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form  id="form-upload">

        <div class="card" id="card">

          <div class="modal-body">

            <!-- /.card -->


            <div class="card-body">





              <input type="file" name="input-image" class="form-control">
              <br>
              <div class="img-container">
                <img id="image">

              </div>
              <br>
              <div class="form-group">
                <label >Kelas</label>
                <select name="input-kelas" id="input-kelas" class="form-control" required>

                  <option value="">Pilih Kelas</option>
                  <option value="1">Buah</option>

                </select>
              </div>
              {% csrf_token %}





            </div>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="btn-save">Save changes</button>
          </div>


        </div>
      </form>

    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.content -->

<div id="modal-large"  data-iziModal-fullscreen="true" style="display:none">

  <div id="content-hasil" class="mt-2">

    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>RGB Image</p>
            </div>
            <img  class="center-image-card" id="image-clean" src="{% static 'images/empty-images.png' %}" alt="">
            <br>
            <div class="text-center mt-2">
              <div class="btn-group-horizontal">
                <button type="button" class="btn btn-info btn-download" data-type="R">R CSV</button>
                <button type="button" class="btn btn-info btn-download" data-type="G">G CSV</button>
                <button type="button" class="btn btn-info btn-download" data-type="B">B CSV</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>Gray Image</p>
            </div>
            <img  class="center-image-card" id="image-gray" src="{% static 'images/empty-images.png' %}" alt="">
            <br>

            <div class="text-center mt-2">
              <button class="btn btn-info btn-download" type="button" data-type="gray" id="btn-download-gray">Gray CSV</button>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>Binary Image</p>
            </div>
            <img  class="center-image-card" id="image-binary" src="{% static 'images/empty-images.png' %}" alt="">
            <br>
            
            <div class="text-center mt-2">
              <button class="btn btn-info btn-download" type="button" data-type="binary" id="btn-download-binary" >Binary CSV</button>
            </div>
          </div>
        </div>
      </div>


    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>H Image</p>
            </div>
            <img  class="center-image-card" id="image-h" src="{% static 'images/empty-images.png' %}" alt="">
            <br>
            <div class="text-center mt-2">
              <div class="btn-group-horizontal">
                <button type="button" class="btn btn-info btn-download" data-type="H">H</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>S Image</p>
            </div>
            <img  class="center-image-card" id="image-s" src="{% static 'images/empty-images.png' %}" alt="">
            <br>
            <div class="text-center mt-2">
              <div class="btn-group-horizontal">
                <button type="button" class="btn btn-info btn-download" data-type="S">S</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="text-center" style="font-weight:bold">
              <p>V Image</p>
            </div>
            <img  class="center-image-card" id="image-v" src="{% static 'images/empty-images.png' %}" alt="">
            <br>
            <div class="text-center mt-2">
              <div class="btn-group-horizontal">
                <button type="button" class="btn btn-info btn-download" data-type="V">V</button>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>
{% endblock content %}

{% block export-js %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/cropperjs/dist/cropper.min.js' %}"></script>
{% endblock export-js %}

{% block js %}
<script>
var $modalUpload = $("#modal-default");
var $btnShowModal = $("#btn-tambah");
var $inputImg = $("input[name='input-image']");
var $inputKelas = $("input[name='input-kelas']");
var image = $("#image");
var filename;
var cropper;

var detail_id


$("#modal-large").iziModal({
  history: false,
  title: "Keterangan",
    // subtitle: "Simple, complete and lightweight modal plugin with jquery.",
    icon: 'icon-chat',
    // overlayColor: 'rgba(255, 255, 255, 0.4)',
    // headerColor: '#334c7b',
    iconColor: 'white',
    // fullscreen: true,
    width: 700,
    padding: 20,
    // rtl: true,
    bodyOverflow: true,
    openFullscreen: true,
    // closeButton: false,
    // top: 50,
    // bottom: 50,
    onClosed: function(modal){
      history.replaceState(null, "", window.location.pathname)
        // console.info(modal)
        //modal.destroy();
      },
      onOpening: function(modal){
        // if (model_id == null) {
        //     history.replaceState(null, "", window.location.pathname)
        //     modal.close();
        // }
        modal.startLoading();
      },
      onOpened: function(modal){
        modal.stopLoading();
        setTimeout(function(){
          $("#modal-large .iziModal-wrap").scrollTop(0);            
        },1)
      }
    });
$("#modal-large").iziModal('setZindex', 99999);


$("#table-data-master").DataTable({
  "scrollX": true,
});

$btnShowModal.click(function() {
  $modalUpload.modal("show");
});




function deleteData(id) {
 $.ajax({
  headers: {'X-CSRFToken': csrftoken.value},
  type: "POST",
  dataType: "json",
  url: "{% url 'buah/hapus_data' %}",
  data: {data_id: id},
  beforeSend: function(){
  }
})
 .done(function(result) {
  if (result.success == 1) {

    window.location.reload(false);
  }
})
 .always(function() {

 })
}


</script>

<script>
$('#table-data-master').on('click','.image-data',function () {


  var id = $(this).closest("tr").data("modelId");
  detail_id = id;
  $.ajax({
    headers: {'X-CSRFToken': csrftoken.value},
    type: "POST",
    dataType: "json",
    url: "{% url 'buah/detail_gambar' %}",
    data: {id:id},
    beforeSend: function(){

    }
  })
  .done(function(result) {
    if (result.success == 1) {

      $("#image-clean").attr("src", "data:image/png;base64,"+(result.image_clean));
      $("#image-gray").attr("src", "data:image/png;base64,"+(result.image_gray));
      $("#image-binary").attr("src", "data:image/png;base64,"+(result.image_binary));
      $("#image-h").attr("src", "data:image/png;base64,"+(result.image_h));
      $("#image-s").attr("src", "data:image/png;base64,"+(result.image_s));
      $("#image-v").attr("src", "data:image/png;base64,"+(result.image_v));


      $("#modal-large").iziModal("open");

    }
  })

  .always(function() {

  });


  

});


$(".btn-download").click(function() {
  var type = $(this).data('type');
  var id = detail_id;

  var data = {
    type: type,
    id: id,
  };

  var url = '{% url "buah/download_csv" %}';
  strUrl = url.substring(0, url.length-1) + "?"+$.param(data);

  $("body").append('<iframe id="firam" src="'+strUrl+'" style="display: none;" ></iframe>');
});
</script>

{% endblock js %}